In [1]:
### 1. Chuẩn bị dữ liệu

In [2]:
import pandas as pd
df=pd.read_csv('shopeep_koreantop_clothing_shop_data.csv')
df

,pk_shop,date_collected,shopid,name,join_month,join_day,join_year,item_count,follower_count,response_time,response_rate,shop_location,rating_bad,rating_good,rating_normal,rating_star,is_shopee_verified,is_official_shop
0,20210613254711738,2021-06-13,254711738,hello.may.ph,April,27,2020,446,17487,10:13:55,96,NaN,181,17510,729,4.81,1,0
1,20210613314198143,2021-06-13,314198143,love.women.shop,September,25,2020,263,8574,10:43:05,73,"San Nicolas,Metro Manila",78,2656,198,4.68,0,0
2,2021061310377223,2021-06-13,10377223,R&O RedOrange,September,27,2016,209,660417,08:32:07,90,"Pasay City,Metro Manila",4647,1071829,18073,4.91,1,0
3,2021061321407329,2021-06-13,21407329,patriciacai,April,30,2017,165,18787,09:10:38,94,"Binondo,Metro Manila",44,18959,215,4.94,1,0
4,2021061311187885,2021-06-13,11187885,Little Market Manila,October,18,2016,467,67371,11:40:59,89,"Caloocan City,Metro Manila",680,39252,2383,4.73,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,20210706449182992,2021-07-06,449182992,Yacent_thrift_Clo,May,22,2021,16,115,08:45:30,86,"Legazpi City,Albay",0,32,0,5.00,0,0
742,20210706396605392,2021-07-06,396605392,Akistore.ph,March,3,2021,84,84,08:01:23,91,NaN,1,9,0,4.60,0,0
743,20210706360379308,2021-07-06,360379308,Yzanice Shop,December,20,2020,78,5982,08:46:30,96,NaN,16,463,16,4.75,1,0
744,2021070629392066,2021-07-06,29392066,Clairecvc Shop,August,2,2017,964,44029,12:19:44,73,"Binondo,Metro Manila",1960,103289,3982,4.78,0,0
745,2021070625811092,2021-07-06,25811092,angelcity.💋,June,17,2017,272,868370,10:02:42,36,"Pasay City,Metro Manila",13401,708666,30799,4.77,0,0

In [ ]:
# Để đơn giản ta thực hiện lọc tập dữ liệu ban đầu theo các thuộc tính sau
df = df[['date_collected','shop_location','response_time']]
df

### 2. Tách cột dữ liệu có kiểu chuỗiTa có thể sử dụng các phép toán tách chuỗi splitHàm str.split(‘Ký tự phân cách’) có tác dụng tách chuỗi ban đầu str thành các chuỗi con được ngăn cách nhau bởi ký tự phân cách

In [3]:
# Tách cột shop_location thành 2 cột District và City

df['District']=df['shop_location'].str.split(',').str[0]
df['City']=df['shop_location'].str.split(',').str[1]
df

,pk_shop,date_collected,shopid,name,join_month,join_day,join_year,item_count,follower_count,response_time,response_rate,shop_location,rating_bad,rating_good,rating_normal,rating_star,is_shopee_verified,is_official_shop,District,City
0,20210613254711738,2021-06-13,254711738,hello.may.ph,April,27,2020,446,17487,10:13:55,96,NaN,181,17510,729,4.81,1,0,NaN,NaN
1,20210613314198143,2021-06-13,314198143,love.women.shop,September,25,2020,263,8574,10:43:05,73,"San Nicolas,Metro Manila",78,2656,198,4.68,0,0,San Nicolas,Metro Manila
2,2021061310377223,2021-06-13,10377223,R&O RedOrange,September,27,2016,209,660417,08:32:07,90,"Pasay City,Metro Manila",4647,1071829,18073,4.91,1,0,Pasay City,Metro Manila
3,2021061321407329,2021-06-13,21407329,patriciacai,April,30,2017,165,18787,09:10:38,94,"Binondo,Metro Manila",44,18959,215,4.94,1,0,Binondo,Metro Manila
4,2021061311187885,2021-06-13,11187885,Little Market Manila,October,18,2016,467,67371,11:40:59,89,"Caloocan City,Metro Manila",680,39252,2383,4.73,1,0,Caloocan City,Metro Manila
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,20210706449182992,2021-07-06,449182992,Yacent_thrift_Clo,May,22,2021,16,115,08:45:30,86,"Legazpi City,Albay",0,32,0,5.00,0,0,Legazpi City,Albay
742,20210706396605392,2021-07-06,396605392,Akistore.ph,March,3,2021,84,84,08:01:23,91,NaN,1,9,0,4.60,0,0,NaN,NaN
743,20210706360379308,2021-07-06,360379308,Yzanice Shop,December,20,2020,78,5982,08:46:30,96,NaN,16,463,16,4.75,1,0,NaN,NaN
744,2021070629392066,2021-07-06,29392066,Clairecvc Shop,August,2,2017,964,44029,12:19:44,73,"Binondo,Metro Manila",1960,103289,3982,4.78,0,0,Binondo,Metro Manila
745,2021070625811092,2021-07-06,25811092,angelcity.💋,June,17,2017,272,868370,10:02:42,36,"Pasay City,Metro Manila",13401,708666,30799,4.77,0,0,Pasay City,Metro Manila

### 3. Tách cột dữ liệu có kiểu ngày tháng

In [4]:
# Tách cột date_collected thành 3 cột Day, Month, Year

df['Day']=pd.to_datetime(df['date_collected'],format='%Y-%m-%d').dt.day
df['Month']=pd.to_datetime(df['date_collected'],format='%Y-%m-%d').dt.month
df['Year']=pd.to_datetime(df['date_collected'],format='%Y-%m-%d').dt.year
df

,pk_shop,date_collected,shopid,name,join_month,join_day,join_year,item_count,follower_count,response_time,...,rating_good,rating_normal,rating_star,is_shopee_verified,is_official_shop,District,City,Day,Month,Year
0,20210613254711738,2021-06-13,254711738,hello.may.ph,April,27,2020,446,17487,10:13:55,...,17510,729,4.81,1,0,NaN,NaN,13,6,2021
1,20210613314198143,2021-06-13,314198143,love.women.shop,September,25,2020,263,8574,10:43:05,...,2656,198,4.68,0,0,San Nicolas,Metro Manila,13,6,2021
2,2021061310377223,2021-06-13,10377223,R&O RedOrange,September,27,2016,209,660417,08:32:07,...,1071829,18073,4.91,1,0,Pasay City,Metro Manila,13,6,2021
3,2021061321407329,2021-06-13,21407329,patriciacai,April,30,2017,165,18787,09:10:38,...,18959,215,4.94,1,0,Binondo,Metro Manila,13,6,2021
4,2021061311187885,2021-06-13,11187885,Little Market Manila,October,18,2016,467,67371,11:40:59,...,39252,2383,4.73,1,0,Caloocan City,Metro Manila,13,6,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,20210706449182992,2021-07-06,449182992,Yacent_thrift_Clo,May,22,2021,16,115,08:45:30,...,32,0,5.00,0,0,Legazpi City,Albay,6,7,2021
742,20210706396605392,2021-07-06,396605392,Akistore.ph,March,3,2021,84,84,08:01:23,...,9,0,4.60,0,0,NaN,NaN,6,7,2021
743,20210706360379308,2021-07-06,360379308,Yzanice Shop,December,20,2020,78,5982,08:46:30,...,463,16,4.75,1,0,NaN,NaN,6,7,2021
744,2021070629392066,2021-07-06,29392066,Clairecvc Shop,August,2,2017,964,44029,12:19:44,...,103289,3982,4.78,0,0,Binondo,Metro Manila,6,7,2021
745,2021070625811092,2021-07-06,25811092,angelcity.💋,June,17,2017,272,868370,10:02:42,...,708666,30799,4.77,0,0,Pasay City,Metro Manila,6,7,2021

### 4. Tách cột dữ liệu có kiểu thời gian

In [5]:
# Tách cột response_time thành 3 cột Hour, Minute, Second
df['Hour']=pd.to_datetime(df['response_time'],format=' %H:%M:%S').dt.hour
df['Minute']=pd.to_datetime(df['response_time'],format=' %H:%M:%S').dt.minute
df['Second']=pd.to_datetime(df['response_time'],format=' %H:%M:%S').dt.second
df

,pk_shop,date_collected,shopid,name,join_month,join_day,join_year,item_count,follower_count,response_time,...,is_shopee_verified,is_official_shop,District,City,Day,Month,Year,Hour,Minute,Second
0,20210613254711738,2021-06-13,254711738,hello.may.ph,April,27,2020,446,17487,10:13:55,...,1,0,NaN,NaN,13,6,2021,10,13,55
1,20210613314198143,2021-06-13,314198143,love.women.shop,September,25,2020,263,8574,10:43:05,...,0,0,San Nicolas,Metro Manila,13,6,2021,10,43,5
2,2021061310377223,2021-06-13,10377223,R&O RedOrange,September,27,2016,209,660417,08:32:07,...,1,0,Pasay City,Metro Manila,13,6,2021,8,32,7
3,2021061321407329,2021-06-13,21407329,patriciacai,April,30,2017,165,18787,09:10:38,...,1,0,Binondo,Metro Manila,13,6,2021,9,10,38
4,2021061311187885,2021-06-13,11187885,Little Market Manila,October,18,2016,467,67371,11:40:59,...,1,0,Caloocan City,Metro Manila,13,6,2021,11,40,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,20210706449182992,2021-07-06,449182992,Yacent_thrift_Clo,May,22,2021,16,115,08:45:30,...,0,0,Legazpi City,Albay,6,7,2021,8,45,30
742,20210706396605392,2021-07-06,396605392,Akistore.ph,March,3,2021,84,84,08:01:23,...,0,0,NaN,NaN,6,7,2021,8,1,23
743,20210706360379308,2021-07-06,360379308,Yzanice Shop,December,20,2020,78,5982,08:46:30,...,1,0,NaN,NaN,6,7,2021,8,46,30
744,2021070629392066,2021-07-06,29392066,Clairecvc Shop,August,2,2017,964,44029,12:19:44,...,0,0,Binondo,Metro Manila,6,7,2021,12,19,44
745,2021070625811092,2021-07-06,25811092,angelcity.💋,June,17,2017,272,868370,10:02:42,...,0,0,Pasay City,Metro Manila,6,7,2021,10,2,42